Run software as another user

diff --git a/web_stack_debugging_2/0-iamsomeoneelse b/web_stack_debugging_2/0-iamsomeoneelse
--- a/web_stack_debugging_2/0-iamsomeoneelse
+++ b/web_stack_debugging_2/0-iamsomeoneelse
@@ -1,3 +1,14 @@
+
 #!/usr/bin/env bash
-# Check if exactly one argument is provided
-sudo -u "$1" whoami
+# A shell script that accept argument
+if [ $# -ne 1 ]; then
+  echo "Usage: $0 <username>"
+  exit 1
+fi
+username="$1"
+if ! id -u "$username" &>/dev/null; then
+  echo "Error: User '$username' does not exist."
+  exit 1
+fi
+sudo -u "$username" whoami
+exit 0
